package com.xqs.entity;
// Generated 2017-11-7 16:24:02 by Hibernate Tools 3.4.0.CR1

import java.util.Date;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * SysApp generated by hbm2java
 */
@Table(name = "app")
@DynamicInsert
@DynamicUpdate
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString
public class App extends IdEntity<App> implements java.io.Serializable {
	private String name;
	
	@Column(name = "context_path")
	private String contextPath;
	
	@Column(name = "app_key")
	private String appKey;
	
	@Column(name = "app_secret")
	private String appSecret;
	
	private Boolean available;
	
	@Column(name = "create_time")
	private Date createTime;
	
	@Column(name = "update_time")
	private Date updateTime;
}
