package com.xqs.entity;
// Generated 2017-11-3 17:03:53 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.util.StringUtils;

import lombok.AllArgsConstructor;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * SysRole generated by hbm2java
 */
@Table(name = "role")
@DynamicInsert
@DynamicUpdate
@Entity
@Getter
@Setter
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(callSuper = true)
@ToString
public class Role extends IdEntity<Role> implements java.io.Serializable {
	@JoinColumn(name = "app_id")
	@ManyToOne(targetEntity = com.xqs.entity.App.class, fetch = FetchType.EAGER)
	private App app;

	private String role;

	private String description;

	@Column(name = "feature_ids")
	private String featureIds;

	@Column(name = "parent_id")
	private Long parentId;

	@Column(name = "parent_ids")
	private String parentIds;

	private Boolean available;

	@Column(name = "create_time")
	private Date createTime;

	@Column(name = "update_time")
	private Date updateTime;

	/**
	 * 获取角色拥有的所有功能的id集合
	 * 
	 * @return
	 */
	public List<Long> getFeatures() {
		List<Long> result = new ArrayList<Long>();
		if (!StringUtils.isEmpty(this.featureIds)) {
			String[] array = this.featureIds.split(",");
			if (array.length > 0) {
				for (String featureId : array) {
					result.add(Long.valueOf(featureId));
				}
			}
		}
		return result;
	}
}
