package com.xqs.entity;
// Generated 2017-11-3 17:03:53 by Hibernate Tools 3.4.0.CR1

import java.util.ArrayList;
import java.util.Date;
import java.util.List;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.ManyToMany;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

import org.apache.shiro.crypto.hash.Md5Hash;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;
import org.springframework.util.StringUtils;

import com.xqs.entity.Feature.FeatureType;

import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.EqualsAndHashCode;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;

/**
 * SysUser generated by hbm2java
 */
@Table(name = "user")
@DynamicInsert
@DynamicUpdate
@Entity
@Data
@NoArgsConstructor
@AllArgsConstructor
public class User extends IdEntity<User> implements java.io.Serializable {
	@Column(name = "organization_id")
	private Long organizationId;

	@JoinColumn(name = "app_id")
	@ManyToOne(targetEntity = com.xqs.entity.App.class, fetch = FetchType.EAGER)
	private App app;

	private String username;

	private String password;

	private String salt;

	@ManyToMany(cascade = { CascadeType.ALL })
	private Set<Role> role;

	private Boolean locked;

	@Column(name = "create_time")
	private Date createTime;

	@Column(name = "update_time")
	private Date updateTime;

	public User(Long organizationId, App app, String username, String password, Set<Role> role, Boolean locked) {
		this.organizationId = organizationId;
		this.app = app;
		this.username = username;
		this.password = password;
		this.role = role;
		this.locked = locked;
	}

	public String getCredentialsSalt() {
		return username + salt;
	}

	public static void main(String[] args) {
		System.out.println(new Md5Hash("123", "8d78869f470951332959580424d4bf4f").toString());
	}
}
